### ISSUE TITLE
Firebase upload suddenly won't work

### ISSUE THREAD

**Issue by kennedc** [wkh237/react-native-fetch-blob#179]
I am using 

    "firebase": "^3.6.0",
    "react": "15.3.2",
    "react-native": "0.37.0",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-fetch-blob": "^0.10.0",
    "react-native-vector-icons": "^3.0.0",
    "react-native-video": "^0.9.0"

And i'm trying to upload a video recorded with react-native-video to firebase - this worked but suddenly it stopped working and now it doesn't succeed.

I'm using the following code where this.props.file.path looks something like this:

file:///storage/emulated/0/Pictures/vidid.mp4
```
  accept = () => {
    let rnfbURI = RNFetchBlob.wrap(this.props.file.path)
    Blob
    .build(rnfbURI, { type : 'video/mp4;'})
    .then((blob) => {
      // upload image using Firebase SDK
      firebase.storage()
        .ref()
        .child('testImageName')
        .put(blob, { contentType : 'video/mp4' })
        .then((snapshot) => {
          console.log(snapshot)
          blob.close()
          done()
        })
    })
}
```
I tried writing Firebase support, but then won't help me since this is a workaround.

My blob object looks like this:

```
 { listeners: {},
   isRNFetchBlobPolyfill: true,
   multipartBoundary: null,
   _ref: 'file:///storage/emulated/0/Pictures/VID_20161113_142100.mp4',
   _blobCreated: true,
   _closed: false,
   cacheName: 'blob-559cd5c4-e880-4742-a3fe-dfae7e1a0df0',
   type: 'video/mp4;',
   size: '3665375' }
```

**Comment by kenmaca** [comment]
May be related to #180?

Is the Firebase error related to the "wrong offset"?

**Comment by kennedc** [comment]
It doesn't give any error - it just stalls at zero procent uploaded.

**Comment by Catuna** [comment]
We are experiencing the same issue with iOS: The upload might actually succeed (seems to be with small files) but the the Firebase API upload callback is never called. (Even if the upload was successful and the file appears in storage).

We tested with release build iOS and development Android. Development Android works perfectly. Release iOS experiences this issue. Haven't tested with development build iOS.

**Comment by wkh237** [comment]
Well, I'm not be able to reproduce this bug, I think I need more information, the logs from XMLHttpRequest polyfill can be turned on by adding this line : 

```js
XMLHttpRequest.setLog(3);
```

I think it'd helpful !

**Comment by tomershohet** [comment]
I have the same thing on Android, the only thing i did was update my android studio then suddenly the callback won't return. I've tried a couple of different approch, using .then or listen to state - or add an await before the "put" command. 
The result is always the same - the file does get uploaded to the firebase storage but the client never get the callback.

Here is my XMLHttpRequest log:
11-21 18:59:45.292 10418-25443: 'XMLHttpRequest', 'verbose:', 'get readyState', 2
11-21 18:59:45.292 10418-25443: 'XMLHttpRequest', 'verbose:', 2
11-21 18:59:45.308 10418-25443: 'XMLHttpRequest', 'debug:', 'XMLHttpRequest done', 'https://firebasestorage.googleapis.com/v0/b/planme-1383.appspot.com/o?name=posts%2Ftest123', { data: '{\n  "name": "posts/test123",\n  "bucket": "planme-1383.appspot.com",\n  "generation": "1479747585452000",\n  "metageneration": "1",\n  "contentType": "image/jpg",\n  "timeCreated": "2016-11-21T16:59:45.379Z",\n  "updated": "2016-11-21T16:59:45.379Z",\n  "storageClass": "STANDARD",\n  "size": "490",\n  "md5Hash": "Z+XksMhLu5ErgM6Y9Zv8aw==",\n  "contentEncoding": "identity",\n  "crc32c": "m0iZQg==",\n  "etag": "CODPwKmputACEAE=",\n  "downloadTokens": "8b6a0752-98ef-470c-a9a4-f52453842d8f"\n}',
                                                             taskId: '981f0943-19f4-4fb6-afc7-3d9bc80b5b8e',
                                                             type: 'utf8',
                                                             respInfo: 
                                                              { respType: 'json',
                                                                headers: 
                                                                 { 'alt-svc': 'quic=":443"; ma=2592000; v="36,35,34"',
                                                                   server: 'UploadServer',
                                                                   date: 'Mon, 21 Nov 2016 16:59:45 GMT',
                                                                   'content-length': '480',
                                                                   'access-control-allow-origin': '*',
                                                                   'content-type': 'application/json; charset=UTF-8',
                                                                   'access-control-expose-headers': 'X-Firebase-Storage-XSRF',
                                                                   'x-content-type-options': 'nosniff',
                                                                   'x-guploader-uploadid': 'AEnB2UqL-9999-9NIQe8ypZHJFwf97XXl1CRKTLOVWalspwcI2HHiYqDy5UYAnqE1E9zUoRkYrM5oBUMYxepjsnnXC3g50ofFQ' },
                                                                redirects: [ 'https://firebasestorage.googleapis.com/v0/b/planme-1383.appspot.com/o?name=posts%2Ftest123' ],
                                                                timeout: false,
                                                                taskId: '981f0943-19f4-4fb6-afc7-3d9bc80b5b8e',
                                                                state: '2',
                                                                status: 200,
                                                                rnfbEncode: 'utf8' },
                                                             info: [Function],
                                                             array: [Function],
                                                             blob: [Function],
                                                             text: [Function],
                                                             json: [Function],
                                                             base64: [Function],
                                                             flush: [Function],
                                                             path: [Function],
                                                             session: [Function],
                                                             readStream: [Function],
                                                             readFile: [Function] }, { listeners: 
                                                              { abort: [ [Function] ],
                                                                error: [ [Function] ],
                                                                load: [ [Function] ] },
                                                             _onabort: [Function],
                                                             _onerror: [Function],
                                                             _onload: [Function],
                                                             _onloadstart: [Function],
                                                             _onprogress: [Function],
                                                             _ontimeout: [Function],
                                                             _onloadend: [Function],
                                                             upload: 
                                                              { listeners: {},
                                                                _onabort: [Function],
                                                                _onerror: [Function],
                                                                _onload: [Function],
                                                                _onloadstart: [Function],
                                                                _onprogress: [Function],
                                                                _ontimeout: [Function],
                                                                _onloadend: [Function] },
                                                             _readyState: 3,
                                                             _uriType: 'net',
                                                             _response: '',
                                                             _responseText: '',
                                                             _responseHeaders: 
                                                              { 'alt-svc': 'quic=":443"; ma=2592000; v="36,35,34"',
                                                                server: 'UploadServer',
                                                                date: 'Mon, 21 Nov 2016 16:59:45 GMT',
                                                                'content-length': '480',
                                                                'access-control-allow-origin': '*',
                                                                'content-type': 'application/json; charset=UTF-8',
                                                                'access-control-expose-headers': 'X-Firebase-Storage-XSRF',
                                                                'x-content-type-options': 'nosniff',
                                                                'x-guploader-uploadid': 'AEnB2UqL-9999-9NIQe8ypZHJFwf97XXl1CRKTLOVWalspwcI2HHiYqDy5UYAnqE1E9zUoRkYrM5oBUMYxepjsnnXC3g50ofFQ' },
                                                             _responseType: '',
                                                             _responseURL: '',
                                                             _responseXML: '',
                                                             _status: 200,
                                                             _statusText: 200,
                                                             _timeout: 60000,
                                                             _sendFlag: true,
                                                             _uploadStarted: true,
                                                             _increment: false,
                                                             _config: {},
                                                             _headers: 
                                                              { 'X-Goog-Upload-Protocol': [Getter/Setter],
                                                                'Content-Type': [Getter/Setter],
                                                                Authorization: [Getter/Setter],
                                                                'X-Firebase-Storage-Version': [Getter/Setter] },
                                                             withCredentials: false,
                                                             _method: 'POST',
                                                             _url: 'https://firebasestorage.googleapis.com/v0/b/planme-1383.appspot.com/o?name=posts%2Ftest123',
                                                             _body: 
                                                              { listeners: {},
                                                                isRNFetchBlobPolyfill: true,
                                                                multipartBoundary: null,
                                                                _ref: '/data/user/0/com.planme/files/RNFetchBlob-blobs/blob-bfd87981-05bd-488a-b6bd-2f9ded892934',
                                                                _blobCreated: true,
                                                                _closed: false,
                                                                cacheName: 'blob-bfd87981-05bd-488a-b6bd-2f9ded892934',
                                                                type: 'text/plain',
                                                                size: 692 },
                                                             _task: 
                                                              { _45: 1,
                                                                _81: 1,
                                                                _65: 
                                                                 { data: '{\n  "name": "posts/test123",\n  "bucket": "planme-1383.appspot.com",\n  "generation": "1479747585452000",\n  "metageneration": "1",\n  "contentType": "image/jpg",\n  "timeCreated": "2016-11-21T16:59:45.379Z",\n  "updated": "2
11-21 18:59:45.309 10418-25443: 'XMLHttpRequest', 'debug:', 'https://firebasestorage.googleapis.com/v0/b/planme-1383.appspot.com/o?name=posts%2Ftest123', { respType: 'json',
                                                             headers: 
                                                              { 'alt-svc': 'quic=":443"; ma=2592000; v="36,35,34"',
                                                                server: 'UploadServer',
                                                                date: 'Mon, 21 Nov 2016 16:59:45 GMT',
                                                                'content-length': '480',
                                                                'access-control-allow-origin': '*',
                                                                'content-type': 'application/json; charset=UTF-8',
                                                                'access-control-expose-headers': 'X-Firebase-Storage-XSRF',
                                                                'x-content-type-options': 'nosniff',
                                                                'x-guploader-uploadid': 'AEnB2UqL-9999-9NIQe8ypZHJFwf97XXl1CRKTLOVWalspwcI2HHiYqDy5UYAnqE1E9zUoRkYrM5oBUMYxepjsnnXC3g50ofFQ' },
                                                             redirects: [ 'https://firebasestorage.googleapis.com/v0/b/planme-1383.appspot.com/o?name=posts%2Ftest123' ],
                                                             timeout: false,
                                                             taskId: '981f0943-19f4-4fb6-afc7-3d9bc80b5b8e',
                                                             state: '2',
                                                             status: 200,
                                                             rnfbEncode: 'utf8' }, 'json'
11-21 18:59:45.309 10418-25443: 'XMLHttpRequest', 'verbose:', 'get responseText', '{\n  "name": "posts/test123",\n  "bucket": "planme-1383.appspot.com",\n  "generation": "1479747585452000",\n  "metageneration": "1",\n  "contentType": "image/jpg",\n  "timeCreated": "2016-11-21T16:59:45.379Z",\n  "updated": "2016-11-21T16:59:45.379Z",\n  "storageClass": "STANDARD",\n  "size": "490",\n  "md5Hash": "Z+XksMhLu5ErgM6Y9Zv8aw==",\n  "contentEncoding": "identity",\n  "crc32c": "m0iZQg==",\n  "etag": "CODPwKmputACEAE=",\n  "downloadTokens": "8b6a0752-98ef-470c-a9a4-f52453842d8f"\n}'
11-21 18:59:45.309 10418-25443: 'XMLHttpRequest', 'debug:', 'request done state = 4'

**Comment by wkh237** [comment]
Okay, I'll setup an 0.37 environment and try reproduce the problem.

**Comment by tomershohet** [comment]
The bug reproduce in 0.36, 0.36.1 and 0.35 as well

בתאריך 22 בנוב׳ 2016 4:03,‏ "wkh237" <notifications@github.com> כתב:

**Comment by tomershohet** [comment]
I see the response data when i put breakpoints in debug mode on the XMLHttpResponse - but it never call any of my events except the error. It is like the firebase javascript sdk won't register well to the events somewhere.

**Comment by sprmn** [comment]
I think I found a related bug when calling `getDownloadURL()` using `"firebase": "^3.6.1"`. If  `window.XMLHttpRequest` is overwritten by the polyfill, the returned promise does not resolve. I tried to look at the logs, but like @tomershohet is saying, everything seems fine with the response data. There is probably some event that firebase waits for, but I can't find it. Debugging the minified firebase code is hard.

**Comment by wkh237** [comment]
@sprmn , thanks for the information. Looks like it may related to the firebase's version since I can't get these error with 3.4.1. I'll look into it.

**Comment by sprmn** [comment]
Yes, it was not present in any version before 3.6.1.

**Comment by sprmn** [comment]
Btw, you'll have to fix #187 in order to debug this, otherwise `getDownloadURL()` will throw an error.

**Comment by tomershohet** [comment]
So i can say for sure that the bug is happening due to something that was change on firebase javascript sdk between 3.5.1 and 3.6.0. 
The callback works on 3.5.1 and stop working from 3.6.0 and farther versions.

**Comment by sprmn** [comment]
@wkh237, I think I found the problem. 

The firebase team probably changed their code in the newer api versions and now uses event listeners for the XMLHttpRequest. The event related code of the XMLHttpRequest polyfill is incorrect. The `dispatchEvent` over [here](https://github.com/wkh237/react-native-fetch-blob/blob/master/src/polyfill/EventTarget.js#L56) expects an event object with a `type` field containing the event type, whereas [here](
https://github.com/wkh237/react-native-fetch-blob/blob/master/src/polyfill/XMLHttpRequest.js#L240) a type is provided to the dispatcher as first argument and the second argument contains the event object. Therefore the listeners are never called, since the `event.type` will always be `undefined`. 

To fix it, either the `dispatchEvent` calls should provide the event object as first argument, or the `dispatchEvent` function itself should accept the type as first argument and the event object as second argument.

**Comment by wkh237** [comment]
FYI, I've published a beta release on npm `0.10.1-beta.1` hopefully this can solve the problem. Please try if it works, thanks !

**Comment by ruci06** [comment]
@wkh237  It works well, thanks!

**Comment by ruci06** [comment]
@wkh237 I thought it was working fine, but uploaded image files broken :'-(

**Comment by kennedc** [comment]
I still can't get it to work with:

    "firebase": "^3.6.1",
    "react-native-fetch-blob": "0.10.1-beta.1",

Using the example from firebase docs it stalls at:

01-05 12:59:55.790 27241  9276 I ReactNativeJS: Upload is 0% done
01-05 12:59:55.790 27241  9276 I ReactNativeJS: Upload is running

`  var path = this.props.file1.path
  Blob.build(RNFetchBlob.wrap(path), { type : 'image/jpeg' })
  .then((blob) => {
    console.log(blob)
    var uploadTask = firebase.storage()
    .ref('rn-firebase-upload')
    .child('testImageName')
    .put(blob, { contentType : 'image/png' })

    uploadTask.on('state_changed', function(snapshot){
      // Observe state change events such as progress, pause, and resume
      // Get task progress, including the number of bytes uploaded and the total number of bytes to be uploaded
      var progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
      console.log('Upload is ' + progress + '% done');
      switch (snapshot.state) {
        case firebase.storage.TaskState.PAUSED: // or 'paused'
        console.log('Upload is paused');
        break;
        case firebase.storage.TaskState.RUNNING: // or 'running'
        console.log('Upload is running');
        break;
      }
    }, function(error) {
      console.log(error)
      // Handle unsuccessful uploads
    }, function() {
      // Handle successful uploads on complete
      // For instance, get the download URL: https://firebasestorage.googleapis.com/...
      var downloadURL = uploadTask.snapshot.downloadURL;
      console.log('feeed nok det virker')
    });
  }
)
`

**Comment by hananurrehman** [comment]
For me it says
Upload is 0% done
Upload is running
Upload is 100% done
Upload is running
 ```
Error: Uncaught (in promise): TypeError: this.uploadTask is undefined
[150]/UploadPage.prototype.phenko/</<@http://localhost:8100/build/main.js:206:21
async/</<@http://localhost:8100/build/vendor.js:125056:13
f</t.prototype.invoke@http://localhost:8100/build/polyfills.js:3:9281
onInvoke@http://localhost:8100/build/vendor.js:4508:28
f</t.prototype.invoke@http://localhost:8100/build/polyfills.js:3:9208
c</r.prototype.run@http://localhost:8100/build/polyfills.js:3:4433
f/<@http://localhost:8100/build/polyfills.js:3:14074
f</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9956
onInvokeTask@http://localhost:8100/build/vendor.js:4499:28
f</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9869
c</r.prototype.runTask@http://localhost:8100/build/polyfills.js:3:5124
o@http://localhost:8100/build/polyfills.js:3:2196
t/this.invoke@http://localhost:8100/build/polyfills.js:3:10985

Stack trace:
c@http://localhost:8100/build/polyfills.js:3:13535
f/<@http://localhost:8100/build/polyfills.js:3:14107
f</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9956
onInvokeTask@http://localhost:8100/build/vendor.js:4499:28
f</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9869
c</r.prototype.runTask@http://localhost:8100/build/polyfills.js:3:5124
o@http://localhost:8100/build/polyfills.js:3:2196
t/this.invoke@http://localhost:8100/build/polyfills.js:3:10985
```

**Comment by JakeNolan** [comment]
@hananurrehman I am seeing this same behavior now that you described above except I don't even get an error returned. I get a successful response but the image never shows up and in the firebase console itself when trying to view the asset it says "Error loading preview". I have noticed that I only see this behavior on images over 350k, my images that fail are all around 650k. This was working fine not too long ago and I haven't changed much around this functionality. Do you recall your fix or workaround by chance?

**Comment by hananurrehman** [comment]
I'm sorry I do not have access to that code now.

**Comment by JakeNolan** [comment]
Shoot, ok thanks anyway.

**Comment by jlsilva10** [comment]
@jSkrills I am facing that same issue now that I upgraded expo to sdk 31.
Did you manage to solve the problem?
