### ISSUE TITLE
How to cancel the HTTPS Request Download

### ISSUE THREAD

**Issue by leo403771872** [wkh237/react-native-fetch-blob#268]
It's ok to stop HTTP Request Download By the function cancel().
However I use the function cancel() to stop a HTTPS Download but crash.
Log is RCTFatalException: Unhandled JS Exception: u.cancel is not a function. (In 'u.cancel()', 'u.cancel' is undefined).
Is this function cann't stop Https Download?

**Comment by wkh237** [comment]
@leo403771872 , does it happens on both IOS and Android?

**Comment by leo403771872** [comment]
Yes, both iOS and Android happen. Log says it' not a function

**Comment by leo403771872** [comment]
@wkh237 Yes, both iOS and Android happen. Log says it' not a function

**Comment by wkh237** [comment]
Could you provide a code snippet about how you use it?  Please also refer to #256 and try if the solution works for you 👍

**Comment by leo403771872** [comment]
@wkh237 I have seen #256 . Our code is almost the same. It's ok to stop Http download, but not in Https

**Comment by wkh237** [comment]
I can replicate this issue on my end now, the cause is that when calling task.cancel() native context does not add the session to request table yet. I've applied a fix at 0b6beae. 

Please try to upgrade your package from the branch

```$
$ npm install --save github:wkh237/react-native-fetch-blob-package#0.10.3-fix-268
```

**Comment by Pedneri1** [comment]
I have exactly the same code, as shown in #256, upgraded to the fix-268 but still get the error
"cancel is not a function". Tried to increase the time of the backoff but it didn't work.

**Comment by Jacse** [comment]
Still experiencing this on `react-native-fetch-blob@0.10.6`

**Comment by wkh237** [comment]
Okay, I can confirm that on Android when either `fileCache` or `path` is set to `config` this problem happens.

**Comment by wkh237** [comment]
I have pushed a fixed version to branch `issue-268` please upgrade your package from the branch if anyone would like to verify it, thanks 💯

**Comment by kesha-antonov** [comment]
@wkh237 

Tried branch ```issue-268```
Not working.

```task.cancel``` gives no error. Downloading continues

**Comment by wkh237** [comment]
@kesha-antonov , thanks for verifying this for us, will look into the issue 👍

**Comment by kaylabranson** [comment]
Still never going to `catch` with `fileCache`

**Comment by slayer49** [comment]
Still getting task.cancel is not a function using 0.10.9 branch installed from github.  I am using eventChannel from redux-saga which requires a function callback to end the process.

Here is my code:

`import { eventChannel, END } from 'redux-saga';
import RNFetchBlob from 'react-native-fetch-blob';
import HomeActions from '../Redux/HomeRedux'

export function downloadFileSagaHelper(track: integer, url: string) {
  // An event channel will let you send an infinite number of events
  // It provides you with an emitter to send these events
  // These events can then be picked up by a saga through a "take" method
  return eventChannel(emitter => {
    let dirs = RNFetchBlob.fs.dirs
    const task = RNFetchBlob.config({
      path : dirs.DocumentDir + '/' + track + '.mp3',
    })
      .fetch('GET', url)
      .progress({ interval: 200 }, (received, total) => {
        const progress = received / total * 100;
        // I chose to emit actions immediately
        emitter(HomeActions.downloadProgress({ track, progress }),
        );
      })
      .then(res => {
        emitter(HomeActions.downloadSuccess({ track, filePath: res.path() }),
        );
        // END event has to be sent to signal that we are done with this channel
        emitter(END);
      })
      .catch(error => {
        // Optional but you can deal with the error here
        console.tron.log(error);
        throw error;
      });

    // The returned method can be called to cancel the channel
    return (error) => {
      task.cancel();
    };
  });
}
`
