### ISSUE TITLE
Undefined on cancel, uploadProgress, downloadProgress when wrapping fetch on RN 0.44

### ISSUE THREAD

**Issue by jjdp** [wkh237/react-native-fetch-blob#370]
The object keys are there yet they are undefined when using the wrapped version. I am on RN 0.44 and rnfb 0.10.5. It is working fine though on rnfb fetch. using android simulator (does it matter)?
```
const Fetch = RNFetchBlob.polyfill.Fetch
window.fetch = new Fetch({}).build()
```

also how do you do formData on the rnfb fetch implementation, since I cant access the functions using the wrapper.

```
const formData = new FormData();
formData.append('key', folder + fileName);
formData.append('acl', acl);
formData.append('Content-Type', mime);
formData.append('X-Amz-Credential', x_amz_credential);
formData.append('X-Amz-Algorithm', 'AWS4-HMAC-SHA256');
formData.append('X-Amz-Date', date);
formData.append('Policy', base64Policy);
formData.append('X-Amz-Signature', signature);
formData.append('file', file);

fetch(url, {
    method : 'POST',
    body : formData
  });
```

**Comment by jjdp** [comment]
@wkh237 any thoughts on this?

**Comment by timothylui** [comment]
I also have this issue, even if I do const fetch = new Fetch({}).build(), the promise that comes back from fetch doesn't have uploadProgress

**Comment by wkh237** [comment]
@jjdp , I've just fixed the issue in 5b43136, you can install the module from branch `issue-370` and verify if the fix works, thank you 👍

**Comment by jjdp** [comment]
im getting this error. is it building for you?
![err](https://user-images.githubusercontent.com/5244520/27010756-cd12ec40-4ede-11e7-9673-24afea413c9a.png)

**Comment by timothylui** [comment]
I can confirm I also get the same build error. IOS uploadProgress working fine on issue-370 branch

**Comment by wkh237** [comment]
@jjdp , thanks for the information, I'll investigate the error and update my progress later.

**Comment by wkh237** [comment]
@jjdp, I've fixed the error, please try again, thanks.

**Comment by jjdp** [comment]
seems ok to me. it returns uploadProgress it doesnt get called after so it just stays at 0%, then again im using s3 formdata.

@timothylui can you check?

**Comment by wkh237** [comment]
@jjdp , thanks for the heads up. Any suggestion on the wiki's instruction ? Will be appriciate about any improvements 👍

**Comment by timothylui** [comment]
@jjdp So with these changes it works fine for me on both android and ios.

The only thing I've found is replacing window.fetch works fine in debug builds but does not work on release builds. If you assign it to a variable instead and use that it works fine.

**Comment by jjdp** [comment]
`Math.floor(loaded/total)` will always return 0 since loaded is lesser than total. You forgot to multiply it by 100.

@timothylui i see, i have only tested debug build on emulator. It maybe because when you compile release on device, the environment is not on the browser anymore. Though Im not too sure about this.

**Comment by CptMaumau** [comment]
Using 0.10.8 and after `RNFetchBlob.fetch` I get `TypeError: undefined is not a function (near '...}).uploadProgress(function (written,...')` on android emulator.

**Comment by jjdp** [comment]
im still on 10.6, have you tried 10.7?

**Comment by CptMaumau** [comment]
Same in 10.6

**Comment by jjdp** [comment]
mine is working though

**Comment by CptMaumau** [comment]
Working now with 10.8, didn't know the order mattered and that it has to be before `.then()`. Learned something, thank you for your time.
